# Generated by Django 4.2.6 on 2023-11-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_produuctgallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProduuctGallery',
            new_name='ProductGallery',
        ),
    ]
