# Generated by Django 4.2.5 on 2023-10-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_Added',
            new_name='date_added',
        ),
    ]
